# Generated by Django 2.2.1 on 2019-11-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parknow',
            name='park',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parknow', to='manager.ParkSpot', verbose_name='车库'),
        ),
    ]
