# Generated by Django 2.2.1 on 2019-11-15 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20191114_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormess',
            name='park',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='error', serialize=False, to='manager.ParkSpot', verbose_name='车库'),
        ),
    ]
