# Generated by Django 2.2.1 on 2019-11-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20191115_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkhis',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出库时间'),
        ),
    ]
