# Generated by Django 2.2.1 on 2019-11-16 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20191116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parknow',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='manager.ParkSpot', unique=True, verbose_name='车库'),
        ),
    ]
