# Generated by Django 2.2.1 on 2019-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20191116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parknow',
            name='begin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='进库时间'),
        ),
    ]
