# Generated by Django 2.2.1 on 2019-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': '管理员账户', 'verbose_name_plural': '管理员账户'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='account',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin_account',
        ),
    ]
